version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/quickflow_db?schema=public
      - JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters
      - JWT_EXPIRATION=1d
      - PORT=3001
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quickflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 